# Generated by Django 4.2.6 on 2024-05-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('marca', models.CharField(max_length=70)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
