# Generated by Django 4.2.6 on 2024-05-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orden_compra',
            fields=[
                ('codigo_orden', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=70)),
                ('rut_proveedor', models.CharField(max_length=9)),
                ('direccion_empresa', models.CharField(max_length=70)),
                ('telefono_proveedor', models.CharField(max_length=70)),
                ('nombre_cliente', models.CharField(max_length=70)),
                ('rut_cliente', models.CharField(max_length=9)),
                ('direccion_cliente', models.CharField(max_length=70)),
                ('telefono_cliente', models.CharField(max_length=70)),
            ],
        ),
    ]
