# Generated by Django 4.2.6 on 2024-05-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orden_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_compra',
            name='telefono_cliente',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orden_compra',
            name='telefono_proveedor',
            field=models.IntegerField(),
        ),
    ]
