# Generated by Django 4.2.6 on 2024-05-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_orden_compra_telefono_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_compra',
            name='telefono_cliente',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='orden_compra',
            name='telefono_proveedor',
            field=models.CharField(max_length=8),
        ),
    ]
