# Generated by Django 4.2.6 on 2024-06-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_orden_delete_orden_compra_delete_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='telefono',
        ),
        migrations.AddField(
            model_name='orden',
            name='telefonoc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orden',
            name='telefonov',
            field=models.IntegerField(default=0),
        ),
    ]
