# Generated by Django 4.2.6 on 2024-06-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_orden_telefono_orden_telefonoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='totalproducto',
            field=models.IntegerField(default=0),
        ),
    ]
