# Generated by Django 4.2.6 on 2024-06-06 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_orden_totalproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='totalproducto',
            new_name='TotalAPagar',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='preciototal',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='preciounidad',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='sumatotal',
        ),
        migrations.AddField(
            model_name='orden',
            name='valorNeto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orden',
            name='iva',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orden',
            name='valorenvio',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=90)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('preciounidad', models.IntegerField()),
                ('totalProducto', models.IntegerField(default=0)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app.orden')),
            ],
        ),
    ]
