# Generated by Django 4.2.6 on 2024-06-06 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_totalproducto_orden_totalapagar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoorden',
            old_name='totalProducto',
            new_name='totalproducto',
        ),
    ]
