# Generated by Django 4.2.6 on 2024-06-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_orden_direccion_entrega_orden_evidencia_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estadoentrega',
            field=models.CharField(choices=[('por_entregar', 'Por entregar'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado')], default='por_entregar', max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('creada', 'creada'), ('rectificada', 'Rectificada')], default='creada', max_length=20),
        ),
    ]
