# Generated by Django 4.2.6 on 2024-06-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_orden_estadoentrega_alter_orden_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='direccion_entrega',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='estadoentrega',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='evidencia_entrega',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='motivo_rechazo',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='rut_recibe',
        ),
    ]
