# Generated by Django 4.2.6 on 2024-06-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_orden_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='estadoentrega',
            field=models.CharField(choices=[('creada', 'creada'), ('rectificada', 'Rectificada'), ('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='orden',
            name='evidencia_entrega',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/'),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='persona_recibe_rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('creada', 'creada'), ('rectificada', 'Rectificada'), ('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado')], default='creada', max_length=20),
        ),
    ]
