# Generated by Django 4.2.6 on 2024-06-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_orden_direccion_entrega_orden_estadoentrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='direccion_entrega',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='estadoentrega',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='evidencia_entrega',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='fecha_rechazo',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='motivo_rechazo',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='persona_recibe_rut',
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('creada', 'creada'), ('rectificada', 'Rectificada')], default='creada', max_length=20),
        ),
    ]
