# Generated by Django 4.2.6 on 2024-06-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_orden_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estadoentrega',
            field=models.CharField(choices=[('creada', 'creada'), ('rectificada', 'Rectificada'), ('por entregar', 'por entregar'), ('entregada', 'entregada'), ('rechazada', 'rechazada')], default='por entregar', max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('creada', 'creada'), ('rectificada', 'Rectificada'), ('por entregar', 'por entregar'), ('entregada', 'entregada'), ('rechazada', 'rechazada')], default='creada', max_length=20),
        ),
    ]
