# Generated by Django 4.2.6 on 2024-06-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_orden_estadoentrega_alter_orden_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('creada', 'creada'), ('rectificada', 'Rectificada')], default='creada', max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estadoentrega',
            field=models.CharField(choices=[('por entregar', 'por entregar'), ('entregada', 'entregada'), ('rechazada', 'rechazada')], default='por entregar', max_length=20),
        ),
    ]
